Filter NSFW posts in Reddit integration
PyDrocsid/cogs pull request #123
Opened 2021-09-07 10:32 UTC by Scriptim

**Description**
Filters NSFW posts from Reddit.

2021-09-15 11:22 UTC, Tristan-H11 approved these changes, later dismissed

2021-09-15 11:24 UTC, Tert0 approved these changes, later dismissed

2021-09-17 19:02 UTC, TheCataliasTNT2k approved these changes, later dismissed

2021-09-18 08:47 UTC, Defelo requested changes
Please add to the `.reddit` embed whether the nsfw filter is enabled or not.

2022-04-03 11:24 UTC, Defelo approved these changes

2022-04-03 11:25 UTC, merged