Be a little friendlier to the Reddit API
PyDrocsid/cogs pull request #125
Opened 2021-09-25 23:51 UTC by Scriptim

**Description**
- A request to the Reddit API sends a user agent string that conforms to the [Reddit API rules](https://github.com/reddit-archive/reddit/wiki/API#rules).
- Posts from multiple subreddits to be sent to the same Discord text channel are all retrieved with a single request, thereby reducing the total number of requests.

**Issue**
This potentially resolves #124.

**Additional Notes**
The number of requests can be further optimized in such a way that _all_ posts are retrieved at once. In this case, the mapping to the correct Discord text channels would have to be done subsequently.

Regarding the settings for the cog, the following changes:
- A Reddit user must be set to be named as the author of the application (i. e. the bot) in the user agent.
- The limit changes its meaning from a per-subreddit limit to a per-textchannel limit.

2021-09-26 06:15 UTC, Tert0 commented on integrations/reddit/cog.py
> +        headers={"User-agent": user_agent()},
`user_agent()` is an async function should it not be awaited?

2021-09-26 06:17 UTC, Tert0 commented on integrations/reddit/cog.py
> +        headers={"User-agent": user_agent()},
`user_agent()` is an async function should it not be awaited?

2021-09-26 06:17 UTC, Tert0 commented on integrations/reddit/cog.py
> +        headers={"User-agent": user_agent()},
`user_agent()` is an async function should it not be awaited?

2021-09-26 06:21 UTC, Tert0 commented
> Note:
Don’t create a session per request. Most likely you need a session per application which performs all requests altogether.
More complex cases may require a session per site, e.g. one for Github and other one for Facebook APIs. Anyway making a session for every request is a very bad idea.
A session contains a connection pool inside. Connection reusage and keep-alives (both are on by default) may speed up total performance.

https://docs.aiohttp.org/en/stable/client_quickstart.html

2021-09-26 07:54 UTC, Scriptim commented on integrations/reddit/cog.py
> +        headers={"User-agent": user_agent()},
sure

2021-09-27 22:21 UTC, TheCataliasTNT2k requested changes

2021-09-27 22:21 UTC, TheCataliasTNT2k commented on integrations/reddit/cog.py
>      async with ClientSession() as session, session.get(
If the user is not set, no api calls should be made to reddit in the entire cog.

2021-09-29 12:37 UTC, Scriptim commented on integrations/reddit/cog.py
>      async with ClientSession() as session, session.get(
should be resolve with 17e591d

2021-09-30 10:35 UTC, Defelo requested changes

2021-09-30 10:35 UTC, Defelo commented on integrations/reddit/cog.py
> +            logger.warning(t.log_no_reddit_author_set)
Please send this warning into the guild's alert channel.

2021-09-30 10:35 UTC, Defelo commented on integrations/reddit/cog.py
> +        await reply(ctx, embed=embed)
You should start the loop here if it was previously disabled.

2021-09-30 10:35 UTC, Defelo commented on integrations/reddit/cog.py
>      async with ClientSession() as session, session.get(
`exists_subreddit` and `get_subreddit_name` are still called when using `.reddit add` and `.reddit remove`, but they don't check if the user is set.

2021-09-30 10:43 UTC, Scriptim commented on integrations/reddit/cog.py
> +        await reply(ctx, embed=embed)
Maybe we should just give a hint that the loop is not running and that one can start it with the trigger command? There might be other reasons why the loop is disabled, and in that case we shouldn't necessarily start the loop every time the author changes.

2021-09-30 10:57 UTC, Scriptim commented on integrations/reddit/cog.py
> +            logger.warning(t.log_no_reddit_author_set)
9e9f225

2021-09-30 10:58 UTC, Scriptim commented on integrations/reddit/cog.py
>      async with ClientSession() as session, session.get(
abdc849

2021-10-03 15:05 UTC, Scriptim commented on integrations/reddit/cog.py
> +        await reply(ctx, embed=embed)
Should be resolved with 22d4fd4

2021-10-04 20:11 UTC, Defelo requested changes
> The limit changes its meaning from a per-subreddit limit to a per-textchannel limit.

Would it be possible to change that back? Or split the posts evenly between the subreddits, so that not x posts are taken from the first subreddit and the others are ignored?

2021-10-04 20:11 UTC, Defelo commented on integrations/reddit/cog.py
> +            await send_alert(t.log_no_reddit_author_set)
```suggestion
            await send_alert(self.bot.guilds[0], t.log_no_reddit_author_set)
```

2022-04-11 17:56 UTC, Scriptim commented
> > The limit changes its meaning from a per-subreddit limit to a per-textchannel limit.
> 
> Would it be possible to change that back? Or split the posts evenly between the subreddits, so that not x posts are taken from the first subreddit and the others are ignored?

It's not that straightforward. The new API calls fetches posts from multiple subreddits at once by having the subreddits concatenated in the URL with a plus. See for example [here](https://www.reddit.com/r/ProgrammerHumor+mathmemes). It is beyond our control how the posts are distributed among the different subreddits, though I guess the distribution is quite fair. In theory, you could rank the posts yourself again, so that they are evenly distributed. In this case, however, you would have to either query more posts than you actually want to send, or query posts repeatedly until you have gathered enough. In a way, this would defeat the purpose of this pull request. I don't think there is a reasonable solution to implement a per-subreddit limit without doing unnecessary API requests again. So I' d advocate leaving it at the per-textchannel limit.

2022-04-11 17:58 UTC, Scriptim commented on integrations/reddit/cog.py
> +            await send_alert(t.log_no_reddit_author_set)
09f8a50416d7b54f2c2ce48cf5430a6b519846d0

2022-07-18 11:12 UTC, Scriptim commented
Hey, jfyi: I will not continue to work on this pull request. If you have any change requests, you'll either have to implement them yourself or simply close the pull request (if I eventually get the impression that it's going stale, I'll close it on my own).

2023-06-09 12:02 UTC, closed without merging