User notes
PyDrocsid/cogs pull request #13
Opened 2021-04-23 12:45 UTC by FlorianJSa

**Description**
Cog for user notes added

**Issue**
No issue 

**Additional Notes**
Nothing to add

2021-04-29 12:47 UTC, Paul-Brauckmann requested changes

2021-04-29 12:47 UTC, Paul-Brauckmann commented on moderation/user_notes/cog.py
> +            applicant=member.mention,
should that be the applicant and therefor the author of the message (`applicant=ctx.author`)?

2021-05-01 18:09 UTC, FlorianJSa commented on moderation/user_notes/cog.py
> +            applicant=member.mention,
Thanks for your hint. Is fixed

2021-05-02 11:16 UTC, Paul-Brauckmann approved these changes

2021-05-21 10:32 UTC, Defelo requested changes
please add descriptions to your commands

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +    async def user_note(self, ctx: Context):
add the read permission check and the guild only decorator here

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +        """
move this into the translations and use the docs decorator instead

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +    @UserNotePermissions.read.check
move this to the user_note command group

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +    async def add_user_note(self, ctx: Context, member: Member, *, message: str):
use the UserMemberConverter instead of Member

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +        await ctx.message.add_reaction(name_to_emoji["white_check_mark"])
send a message to the changelog

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +        user_notes = await db.get(UserNote, message_id=message_id)
please use typing

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +        if user_notes:
raise a CommandError instead of failing silently

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +            await ctx.message.add_reaction(name_to_emoji["white_check_mark"])
send a message to the changelog

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +        user_notes = await db.all(filter_by(UserNote, member=member.id))
use db.stream and an async for loop instead of db.all and a synchronous for loop

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +        embed = Embed(title=t.user_info)
add an embed color

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +        await ctx.send(embed=embed)
use send_long_embed instead of ctx.send

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/models.py
> +    message_id: Union[Column, str] = Column(String(length=10), primary_key=True, unique=True)
use a numeric id with auto increment enabled

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/models.py
> +    applicant: Union[Column, str] = Column(Text(collation="utf8mb4_bin"))
rename to author and save the user id instead

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/permissions.py
> +class UserNotePermissions(BasePermission):
```suggestion
class UserNotePermission(BasePermission):
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/translations/en.yml
> +user_info: "User infos"
why user *infos*?
```suggestion
user_notes: User Notes
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +    @UserNotePermissions.write.check
```suggestion
    @UserNotePermission.write.check
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +from cogs.library.moderation.user_notes.permissions import UserNotePermissions
```suggestion
from cogs.library.moderation.user_notes.permissions import UserNotePermission
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +    @UserNotePermissions.write.check
```suggestion
    @UserNotePermission.write.check
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/translations/en.yml
> +id: "message_id"
```suggestion
id: Message ID
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/translations/en.yml
> +message: "message"
```suggestion
message: Message
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/translations/en.yml
> +timestamp: "timestamp"
```suggestion
timestamp: Timestamp
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/translations/en.yml
> +applicant: "applicant"
```suggestion
author: Author
```

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +from cogs.library.moderation.user_notes.permissions import UserNotePermissions
use pycharm to rearrange imports

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +    async def show_user_note(self, ctx: Context, member: Member):
use the UserMemberConverter instead of Member

2021-05-21 10:32 UTC, Defelo commented on moderation/user_notes/cog.py
> +            embed.add_field(name=t.applicant, value=note.applicant, inline=True)
this won't work

2021-05-21 22:54 UTC, FlorianJSa commented on moderation/user_notes/cog.py
> +        await ctx.message.add_reaction(name_to_emoji["white_check_mark"])
Can you explain what you exactly mean with that

2021-05-21 22:54 UTC, FlorianJSa commented on moderation/user_notes/cog.py
> +            embed.add_field(name=t.applicant, value=note.applicant, inline=True)
In the future it would be helpful if you write what exactly does not work

2021-05-22 09:43 UTC, Defelo requested changes
move the "delete old messages" feature into its own branch

2021-05-22 10:34 UTC, Paul-Brauckmann commented on moderation/user_notes/cog.py
> +        await ctx.message.add_reaction(name_to_emoji["white_check_mark"])
I think he means that u should send a message to the changelog channel with the statement that a note for the user has been added and with the actual content of the message

2021-05-22 20:36 UTC, FlorianJSa commented on moderation/user_notes/cog.py
> +            embed.add_field(name=t.applicant, value=note.applicant, inline=True)
Can you explain what exactly is not working for me everything works perfectly

2021-05-22 20:37 UTC, FlorianJSa commented on moderation/user_notes/cog.py
> +            embed.add_field(name=t.applicant, value=note.applicant, inline=True)
For this reason I will ignore her comment for now

2021-05-22 20:54 UTC, closed without merging