add user_docs
PyDrocsid/cogs pull request #161
Opened 2021-10-03 12:38 UTC by schnitzel4

**Description**
i added docs for user notes
**Issue**
Closes #40 

**Additional Notes**

2021-10-03 15:19 UTC, Tert0 commented on moderation/user_notes/documentation.md
> +.?.user_notes [add|a|+] <member> <content>
Please remove `.?`

2021-10-03 15:33 UTC, Tert0 approved these changes, later dismissed

2021-10-08 13:07 UTC, Tristan-H11 requested changes

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +The `.user_notes add` add a note for a specific user.
```suggestion
The `.user_notes add` command adds a note for a specific user.
```

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +|`member`|:heavy_check_mark:|A member.| |
```suggestion
|`member`|:heavy_check_mark:|A member| |
```

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +Required Permissions:
```suggestion
Required permissions:
```

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +The `.user_notes remove` command remove the user note by note id.
```suggestion
The `.user_notes remove` command removes the user note by note id.
```

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +|`note_id`|:heavy_check_mark:|A note id. You can see|
```suggestion
|`note_id`|:heavy_check_mark:|A note id you can see|
```

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +Required Permissions:
```suggestion
Required permissions:
```

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +The `.user_notes show` command shows all notes of a member.
```suggestion
The `.user_notes show` command shows all notes belonging to a member.
```

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +|`member`|:heavy_check_mark:|A member.|
```suggestion
|`member`|:heavy_check_mark:|A member|
```

2021-10-08 13:07 UTC, Tristan-H11 commented on moderation/user_notes/documentation.md
> +Required Permissions:
```suggestion
Required permissions:
```

2021-10-11 05:37 UTC, schnitzel4 commented
hey @Tristan-H11 hab deine änderungen jetzt eingebaut. Gruß

2021-10-11 05:39 UTC, Tristan-H11 commented
> hey @Tristan-H11 hab deine änderungen jetzt eingebaut. Gruß 

Perfect ^^
@schnitzel4

2021-10-11 07:12 UTC, Tristan-H11 submitted a review, later dismissed

2021-10-11 23:39 UTC, 4norak requested changes

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +
````suggestion


# user_notes

The `.user_notes` command contains subcommands to manage user notes.

```css
.[user_notes|un] [subcommand]
```

````

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +## `add`
```suggestion
### `add`
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +The `.user_notes add` command adds a note for a specific user.
```suggestion
The `add` subcommand is used to add a note to a specific user.
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|`member`|:heavy_check_mark:|A member| |
```suggestion
|`member`|:heavy_check_mark:|A member|
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +## `remove`
```suggestion
### `remove`
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +## `show`
```suggestion
### `show`
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +Required permissions:
```suggestion
Required Permissions:
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +The `.user_notes remove` command removes the user note by note id.
```suggestion
The `remove` subcommand removes a user note by note id.
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|`note_id`|:heavy_check_mark:|A note id You can see|
```suggestion
|`note_id`|:heavy_check_mark:|A note id|
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +Required permissions:
```suggestion
Required Permissions:
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +The `.user_notes show` command shows all notes belonging to a member.
```suggestion
The `show` subcommand shows all notes for a member.
```

2021-10-11 23:39 UTC, 4norak commented on moderation/user_notes/documentation.md
> +Required permissions:
```suggestion
Required Permissions:
```

2021-10-14 10:27 UTC, 4norak requested changes

2021-10-14 10:27 UTC, 4norak commented on moderation/user_notes/documentation.md
> +# user_notes
```suggestion
# UserNoteCog

This cog provides the `.user_notes` command to manage user notes.


## user_notes
```

2021-10-14 12:05 UTC, Defelo requested changes

2021-10-14 12:05 UTC, Defelo commented on moderation/user_notes/documentation.md
> +# UserNoteCog
```suggestion
# User Notes
```

2021-10-14 12:05 UTC, Defelo commented on moderation/user_notes/documentation.md
> +
Add required permissions (`user_notes.read`)

2021-12-11 11:13 UTC, Tristan-H11 commented
@Defelo @4norak any reasons to block this any longer?

2021-12-20 14:57 UTC, Defelo approved these changes, later dismissed

2021-12-21 21:13 UTC, 4norak requested changes

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +This cog provides the `.user_notes` command to manage user notes.
```suggestion
Contains the `.user_notes` command to manage user notes.
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +The `.user_notes` command contains subcommands to manage user notes.
```suggestion
Contains subcommands to manage user notes.
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +The `show` subcommand shows all notes of a specific user.
```suggestion
Shows all notes for a specific user.
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +
```suggestion

Arguments:

```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|Argument|Required|Description|
```suggestion
| Argument | Required           | Description |
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|:------:|:------:|:----------|
```suggestion
|:--------:|:------------------:|:------------|
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|`member`|:fontawesome-solid-check:|A member|
```suggestion
| `member` | :heavy_check_mark: | A member |
```
Is it actually a member or a user?

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +The `add` subcommand is used to add a note to a specific user.
```suggestion
Adds a note to a specific user.
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|Argument|Required|Description|
```suggestion
| Argument  | Required           | Description     |
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|:------:|:------:|:----------|
```suggestion
|:---------:|:------------------:|:----------------|
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|`member`|:fontawesome-solid-check:|A member|
```suggestion
| `member`  | :heavy_check_mark: | A member        |
```
Is it actually a member or a user?

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|`content`|:fontawesome-solid-check:|The note you want to add|
```suggestion
| `content` | :heavy_check_mark: | The note to add |
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +The `remove` subcommand removes a user note by note id.
```suggestion
Removes a user note by note id.
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|`note_id`|:fontawesome-solid-check:|A note id|
```suggestion
| `note_id` | :heavy_check_mark: | A note id   |
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|Argument|Required|Description|
```suggestion
| Argument  | Required           | Description |
```

2021-12-21 21:13 UTC, 4norak commented on moderation/user_notes/documentation.md
> +|:------:|:------:|:----------|
```suggestion
|:---------:|:------------------:|:------------|
```

2021-12-22 16:33 UTC, Defelo approved these changes

2021-12-27 20:57 UTC, 4norak approved these changes

2021-12-27 21:22 UTC, merged