Migrated Polls to Discord Interactions
PyDrocsid/cogs pull request #162
Opened 2021-10-03 17:41 UTC by Tert0

**Description**
- Migrated Polls to Discord Interactions
- (Polls are now anonym)

**Issue**
Closes #140

2021-10-03 17:52 UTC, Tristan-H11 requested changes

2021-10-03 17:52 UTC, Tristan-H11 commented on general/polls/translations/en.yml
> +poll_select_placeholder: Select an Option to Vote!
```suggestion
poll_select_placeholder: Select an option to vote!
```

2021-10-03 17:52 UTC, Tristan-H11 commented on general/polls/translations/en.yml
> +  many: "{} Votes"
```suggestion
  zero: "{} votes"
  one: "{} vote"
  many: "{} votes"
```

2021-10-04 17:49 UTC, Defelo requested changes

2021-10-04 17:49 UTC, Defelo commented on general/polls/translations/en.yml
> +  zero: "{cnt} votes"
you don't need to specify `zero` if it is the same as `many`

2021-12-19 20:55 UTC, Tristan-H11 requested changes

2021-12-19 20:55 UTC, Tristan-H11 commented on general/polls/translations/en.yml
> +option_name_duplicated: "You can't have a duplicated Option!"
```suggestion
option_name_duplicated: "You cannot have duplicate options!"
```

2022-05-09 19:30 UTC, closed without merging