Wikipedia integration
PyDrocsid/cogs pull request #17
Opened 2021-05-19 10:59 UTC by Houseplant1

**Description**
Added a cog which can display the wikipedia artikel of a given string

2021-05-19 11:59 UTC, Paul-Brauckmann requested changes

2021-05-19 11:59 UTC, Paul-Brauckmann commented on integrations/wikipedia/cog.py
> +        super().__init__()
This is unnecessary

2021-05-19 11:59 UTC, Paul-Brauckmann commented on integrations/wikipedia/cog.py
> +        except DisambiguationError as not_found_err:
I think if u just name the DisambiguationError `err` this it would be much more fluent when reading

2021-05-19 11:59 UTC, Paul-Brauckmann commented on integrations/wikipedia/cog.py
> +        except PageError as not_not_found_error:
I think if u just name the PageError `err` this it would be much more fluent when reading

2021-05-19 11:59 UTC, Paul-Brauckmann commented on integrations/wikipedia/cog.py
> +    embed = Embed(title=title, description=content, color=color)
are u shure that the content is short enove that u don't need to embeds? if not consider using the utils from the PyDrocsid lib

2021-05-19 11:59 UTC, Paul-Brauckmann commented on integrations/wikipedia/cog.py
> +                                            requested_by=ctx.author))
Consider using an `else` block for this because it's not the couse of the error.

```python
try:
    summary = await run_in_thread(wikipedia.summary, title)
except:
    # ...
    pass
   
else:
    await ctx.send(embed=make_embed(title=title, content=summary, color=Colors.Wiki,
                                    requested_by=ctx.author))```

2021-05-19 12:11 UTC, Houseplant1 commented on integrations/wikipedia/cog.py
> +    embed = Embed(title=title, description=content, color=color)
cool didnt know about that 
![Screenshot 2021-05-19 141042](https://user-images.githubusercontent.com/77019113/118810366-18822480-b8ac-11eb-8b32-f9517a6ff7b1.png)

2021-05-19 16:28 UTC, Paul-Brauckmann commented on integrations/wikipedia/cog.py
> +            )
is there a possibility that the embed with suggestions is also to long? if so you should consider using `send_long_embed` also to send this embed.

2021-05-19 16:28 UTC, Paul-Brauckmann commented on integrations/wikipedia/cog.py
> +                ))
I am not sure but i would suggest to remove one indentation

2021-05-22 21:05 UTC, Paul-Brauckmann requested changes

2021-05-22 21:05 UTC, ghost commented on integrations/wikipedia/cog.py
> +import wikipedia.exceptions as wx
how about if u import the errors explicit like
```python
from wikipedia.exceptions import DisambiguationError  # ...
```

and consider rearranging the import like defined in [PEP8](https://www.python.org/dev/peps/pep-0008/#imports)

2021-05-22 21:05 UTC, Paul-Brauckmann commented on integrations/wikipedia/cog.py
> +from wikipedia import summary as s
I think this is not helping because s is not clear what u mean later in the code... and it also violates [PEP8](https://www.python.org/dev/peps/pep-0008/#names-to-avoid).
Just make an explicit import like bevor
```python
from wikipedia import summary
```

2021-05-22 21:07 UTC, Paul-Brauckmann commented
an please look at the comment above that i made 
- https://github.com/PyDrocsid/cogs/pull/17#discussion_r635396788
- https://github.com/PyDrocsid/cogs/pull/17#discussion_r635403356

2021-05-23 06:50 UTC, Houseplant1 commented
what should i do about pep8 e501 on line 8?

2021-05-23 15:36 UTC, Paul-Brauckmann commented
> what should i do about pep8 e501 on line 8?

a solution that i would prefere is
```python
from wikipedia.exceptions import WikipediaException, DisambiguationError, PageError  # skipcq: PYL-E501
```
other solution are the following
```python
from wikipedia.exceptions import WikipediaException, DisambiguationError,\
    PageError
from wikipedia.exceptions import (WikipediaException, DisambiguationError,
                                  PageError)
```

2021-05-23 17:21 UTC, Paul-Brauckmann commented
I am sorry to say this but if u want to do it rigth u need to put two spaces before an inline comment

2021-05-24 11:11 UTC, Paul-Brauckmann approved these changes

2021-05-25 12:08 UTC, Paul-Brauckmann approved these changes

2021-05-27 10:48 UTC, Paul-Brauckmann approved these changes

2021-06-05 11:49 UTC, Paul-Brauckmann approved these changes

2021-06-06 16:16 UTC, Paul-Brauckmann approved these changes

2021-06-11 16:06 UTC, merged