MH v3.3
PyDrocsid/cogs pull request #185
Opened 2022-01-03 21:34 UTC by Defelo

2022-01-04 16:12 UTC, Tristan-H11 requested changes

2022-01-04 16:12 UTC, Tristan-H11 commented on administration/roles/translations/en.yml
> +clone_no_permission: I cannot clone this role because I don't have `manage_roles` permission on this server.
```suggestion
clone_no_permission: I cannot clone this role because I do not have `manage_roles` permission on this server.
```

2022-01-04 16:12 UTC, Tristan-H11 commented on general/voice_channel/translations/en.yml
> +no_custom_name: You are not allowed to set a custom channel name! Omit the `name` parameter to choose a random name or pick a name from [theses lists](https://github.com/PyDrocsid/cogs/tree/develop/g
```suggestion
no_custom_name: You are not allowed to set a custom channel name! Omit the `name` parameter to choose a random name or pick a name from [these lists](https://github.com/PyDrocsid/cogs/tree/develop/general/voice_channel/names)!
```

2022-01-04 16:12 UTC, Tristan-H11 commented on moderation/invites/translations/en.yml
> +clear_description: "Are you sure you want to delete the description?"
```suggestion
clear_description: "Are you sure that you want to delete the description?"
```

2022-01-04 16:34 UTC, Tristan-H11 submitted a review, later dismissed

2022-01-06 22:55 UTC, TheCataliasTNT2k approved these changes

2022-01-07 10:09 UTC, merged