VC Bug fix
PyDrocsid/cogs pull request #188
Opened 2022-01-24 20:26 UTC by Tert0

**Description**
VC Bug Fix

**Issue**
Fixed the bug

2022-01-24 20:27 UTC, LoCrealloc submitted a review, later dismissed

2022-01-24 20:28 UTC, NekoFanatic approved these changes, later dismissed

2022-01-24 20:30 UTC, NekoFanatic submitted a review, later dismissed

2022-01-24 20:37 UTC, LoCrealloc submitted a review, later dismissed

2022-01-24 20:53 UTC, NekoFanatic submitted a review, later dismissed

2022-01-24 21:32 UTC, Defelo requested changes

2022-01-24 21:32 UTC, Defelo commented on general/voice_channel/cog.py
> +        c = len(b := [*range(13 - 37 + 42 + 4 >> (1 & 3 & 3 & 7 & ~42))])
```suggestion
        c = len(b := [*range(13 - 37 + 42 + ((4 > 2) << 4 - 2) >> (1 & 3 & 3 & 7 & ~42))])
```

2022-01-28 16:55 UTC, NekoFanatic approved these changes

2022-01-28 16:56 UTC, NekoFanatic approved these changes

2022-01-28 22:53 UTC, Defelo approved these changes

2022-01-28 22:53 UTC, merged