Feature/user notes
PyDrocsid/cogs pull request #19
Opened 2021-05-23 17:39 UTC by FlorianJSa

**Description**
Provide a description of what your changes do.

**Issue**
Closes #XX

**Additional Notes**
Add any other context about the pull request here.

2021-05-24 13:08 UTC, Paul-Brauckmann approved these changes

2021-05-25 22:06 UTC, Defelo requested changes

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +from cogs.library.moderation.user_notes.permissions import UserNotePermission
use relative imports here

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +from library.PyDrocsid.command import docs
```suggestion
from PyDrocsid.command import docs
```

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +t = t.user_notes
```suggestion
tg = t.g
t = t.user_notes
```

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +class UserNoteCog(Cog, name="User notes"):
```suggestion
class UserNotesCog(Cog, name="User Notes"):
```

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +    @UserNotePermission.read.check
```suggestion
    @UserNotePermission.read.check
    @guild_only()
```

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +    @commands.group()
add command aliases

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +    async def add_user_note(self, ctx: Context, member: UserMemberConverter, *, message: str):
add command description

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +    async def remove_user_note(self, ctx: Context, message_id: int):
add command description

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +        user_note: UserNote = await db.get(UserNote, message_id=message_id)
```suggestion
        user_note: Optional[UserNote] = await db.get(UserNote, message_id=message_id)
```

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +        await db.delete(user_note)
use `confirm` from PyDrocsid to create a simple confirmation dialog

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +    async def show_user_note(self, ctx: Context, member: UserMemberConverter):
add command description

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +        await send_long_embed(ctx, embed)
```suggestion
        await send_long_embed(ctx, embed, paginate=True)
```

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +            embed.add_field(name=t.author, value=f"<@{note.author}>", inline=True)
put the entire note into one embed field. you can use the timestamp as the name (as in the `ulog` command)

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/translations/en.yml
> +description: "Mange notes for users"
use a `commands` dictionary to store the command descriptions

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +    @user_note.command(name="add")
add command aliases

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +    @user_note.command(name="remove")
add command aliases

2021-05-25 22:06 UTC, Defelo commented on moderation/user_notes/cog.py
> +    @user_note.command(name="show")
add command aliases

2021-06-11 10:56 UTC, Defelo approved these changes

2021-06-11 10:56 UTC, merged