Discord Token Deleter
PyDrocsid/cogs pull request #32
Opened 2021-06-17 16:06 UTC by Tert0

**Description**
Deletes Discord Bot Tokens in messages

**Issue**
Closes #24

2021-06-17 18:08 UTC, Paul-Brauckmann approved these changes

2021-06-17 21:31 UTC, Defelo requested changes
Please add some newlines to improve code readability.

2021-06-17 21:31 UTC, Defelo commented on general/discord_bot_token_deleter/cog.py
> +import re
Please use PyCharm to reorder the imports

2021-06-17 21:31 UTC, Defelo commented on general/discord_bot_token_deleter/translations/en.yml
> +discord_bot_token_deleter_description: >
You don't need the `discord_bot_token_deleter_` prefix as these translations are already in the `discord_bot_token_deleter` namespace

2021-06-17 21:31 UTC, Defelo commented on general/discord_bot_token_deleter/cog.py
> +            logger.error(error)
Send a custom message into the alert channel by using the `send_alert` PubSub channel instead

2021-06-17 21:31 UTC, Defelo commented on general/discord_bot_token_deleter/cog.py
> +        embed.set_footer(text=tg.requested_by(message.author, message.author.id), icon_url=message.author.avatar_url)
Mention the original author in the message content instead

2021-06-17 21:31 UTC, Defelo commented on general/__init__.py
> +from .discord_bot_token_deleter import DiscordBotTokenDeleter
Please reorder imports

2021-06-19 10:48 UTC, Paul-Brauckmann approved these changes

2021-06-20 15:19 UTC, Defelo approved these changes

2021-06-20 15:19 UTC, merged