Alert for missing perms and wastebasket-reaction for remindMe messages
PyDrocsid/cogs pull request #38
Opened 2021-06-20 19:11 UTC by Tristan-H11

2021-06-21 16:20 UTC, Paul-Brauckmann approved these changes

2021-06-25 04:47 UTC, Defelo requested changes

2021-06-25 04:47 UTC, Defelo commented on general/remind_me/cog.py
> +    """
```suggestion
    """Add a "Remind Me"-functionality by sending the user a message they reacted on."""
```

2021-06-25 04:47 UTC, Defelo commented on general/remind_me/cog.py
> +        Sends an alert in case of missing permissions.
```suggestion
        Check, if the reaction is in a list of set emojis. If so, the message is sent as a direct message to the user.
        Remove the user reaction, if the user does not accept direct messages.
        Send an alert in case of missing permissions.
```

2021-06-25 04:47 UTC, Defelo commented on general/remind_me/cog.py
> +                    return
move this into a new function to avoid duplicate code

2021-06-25 04:47 UTC, Defelo commented on general/remind_me/cog.py
> +        if await check_wastebasket(message_to_user, member, emoji, t.created_by):
`check_wastebasket` cannot be used here, because this function only works for embeds generated and sent by the bot. Also this check should be placed at the top of this event handler.

2021-07-06 19:28 UTC, Defelo requested changes

2021-07-06 19:28 UTC, Defelo commented on general/remind_me/cog.py
> +    """Remove the 'RemindMe-Reaction' from a member, if he does not allow private messages."""
```suggestion
    """Remove the RemindMe reaction from a member, if they do not allow private messages."""

```

2021-07-06 19:28 UTC, Defelo commented on general/remind_me/cog.py
> +        await message.remove_member_reaction(emoji, member)
This method does not exist. Please test your code before committing.

2021-07-06 19:28 UTC, Defelo commented on general/remind_me/translations/en.yml
> +cannot_send: Cannot remove RemindMe-reaction from {}. Missing permission `MANAGE_MESSAGES`.
```suggestion
cannot_send: Could not remove RemindMe reaction from {} because I don't have `manage_messages` permission.
```

2021-07-06 19:28 UTC, Defelo commented on general/remind_me/cog.py
> +    """Add a "Remind Me"-functionality by sending the user a message they reacted on."""
```suggestion
    """Add a "Remind Me"-functionality by sending the user a copy of the message they reacted on."""
```

2021-07-07 07:44 UTC, Defelo approved these changes

2021-07-07 08:05 UTC, merged