Added Verification Docs
PyDrocsid/cogs pull request #92
Opened 2021-07-20 18:48 UTC by Tert0

**Issue**
Closes #51

2021-07-20 19:11 UTC, Tristan-H11 requested changes

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +This Cog is used to add a Verification System.
```suggestion
This Cog is used to add a verification system.
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +With the `add` subcommand you can a Verification Role.
```suggestion
With the `add` subcommand you can add a verification role.
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +You can set `reverse` to `true` then the Role will get removed from the user and not added.
```suggestion
If you set `reverse` to `true`, the role will be removed from the user instead of added.
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +role     | :heavy_check_mark:  | The Verification Role
```suggestion
role     | :heavy_check_mark:  | The verification role
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +reverse  |                     | The Role assignment will be reversed => Role will get removed
```suggestion
reverse  |                     | The role assignment will be reversed => role will be removed
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +Required Permissions:
```suggestion
Required permissions:
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +Set the Time you have to be on the Server until you can Verify.
```suggestion
Set the time a user has to be on the server until they can verify.
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +delay    | :heavy_check_mark:  | The Time in Seconds
```suggestion
delay    | :heavy_check_mark:  | The time in seconds
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +Sets the *Secret* Password you'll need to Verify.
```suggestion
Sets the *secret* password the user will need to verify.
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +password | :heavy_check_mark:  | The Password as string
```suggestion
password | :heavy_check_mark:  | The password as string
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +    Password has a Max-Length of 256 Chars
```suggestion
    The password has a max-length of 256 characters.
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +Removes an existing Verification.
```suggestion
Removes an existing verification.
```

2021-07-20 19:11 UTC, Tristan-H11 commented on moderation/verification/documentation.md
> +role     | :heavy_check_mark:  | The Verification Role
```suggestion
role     | :heavy_check_mark:  | The verification role
```

2021-07-21 20:33 UTC, Tristan-H11 submitted a review, later dismissed

2021-09-27 22:27 UTC, 4norak requested changes

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +`role`     | :heavy_check_mark:  | The verification role
```suggestion
`role`|:heavy_check_mark:|The verification role
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +`reverse`  |                     | Remove this role instead of adding it to the user.
```suggestion
`reverse`|       |Remove this role instead of adding it to the user.
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +Argument | Required            | Description
```suggestion
Argument|Required|Description
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +Argument | Required            | Description
```suggestion
Argument|Required|Description
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +`role`     | :heavy_check_mark:  | The verification role
```suggestion
`role`|:heavy_check_mark:|The verification role
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +---------|---------------------|------------
```suggestion
|:------:|:------:|:----------|
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +---------|---------------------|------------
```suggestion
|:------:|:------:|:----------|
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +The `password` subcommand sets the *secret* password the user will need to verify.
```suggestion
The `password` subcommand sets the *secret* password the user will need to verify with.
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +Argument | Required            | Description
```suggestion
Argument|Required|Description
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +---------|---------------------|------------
```suggestion
|:------:|:------:|:----------|
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +`password` | :heavy_check_mark:  | The password as string
```suggestion
`password`|:heavy_check_mark:|The password
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +Argument | Required            | Description
```suggestion
Argument|Required|Description
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +---------|---------------------|------------
```suggestion
|:------:|:------:|:----------|
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +`delay`    | :heavy_check_mark:  | The amount of time in seconds
```suggestion
`delay`|:heavy_check_mark:|The amount of time in seconds
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +The `verify` command is used by server members to verify themselves. If the specified password is correct and the configured delay has elapsed, the configured verification roles will be added or remo
```suggestion
The `verify` command is used by server members to verify themselves. If the specified password is correct and the configured delay has elapsed, the configured verification roles will be added to or removed from the member.
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +The `.verification` command shows the current verification configuration. This includes the roles that will be added or removed from the user (verification roles), the configured password and the amo
```suggestion
The `.verification` command shows the current verification configuration. This includes the roles that will be added to or removed from the member (verification roles), the configured password and the amount of time a member has to be in the server before they can verify.
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +Argument | Required            | Description
```suggestion
Argument|Required|Description
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +---------|---------------------|------------
```suggestion
|:------:|:------:|:----------|
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +`password` | :heavy_check_mark:  | The verification password
```suggestion
`password`|:heavy_check_mark:|The verification password
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +    As this command can only be used in private messages, it does not start with the configured bot prefix! So, for example, if the configured password is `Tr0ub4dor&3` a user would have to send this
```suggestion
    As this command can only be used in direct messages, it does not start with the configured bot prefix! So, for example, if the configured password is `Tr0ub4dor&3`, a member would have to send this exact message to the bot to complete verification:
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +This cog is used to add a verification system that adds or removes certain roles from a user when they send the bot a command with a pre-set password via direct messages.
```suggestion
This cog is used to add a verification system that adds or removes certain roles from a member when they send the bot a command with a pre-set password via direct messages.
```

2021-09-27 22:27 UTC, 4norak commented on moderation/verification/documentation.md
> +The `delay` subcommand sets the amount of time a user has to be on the server before they can verify.
```suggestion
The `delay` subcommand sets the amount of time a member has to be in the server before they can verify.
```

2021-10-02 15:18 UTC, Tristan-H11 submitted a review, later dismissed

2021-10-02 21:14 UTC, Defelo submitted a review, later dismissed

2021-10-03 01:59 UTC, 4norak requested changes

2021-10-03 01:59 UTC, 4norak commented on moderation/verification/documentation.md
> +The `add` subcommand adds a verification role. If you set `reverse` to `true`, the role will be removed from the user instead of being added. Note that verification will fail if the user does not hav
```suggestion
The `add` subcommand adds a verification role. If you set `reverse` to `true`, the role will be removed from the member instead of being added. Note that verification will fail if the member does not have all reverse verification roles!
```

2021-10-03 01:59 UTC, 4norak commented on moderation/verification/documentation.md
> +|`reverse`|       |Remove this role instead of adding it to the user.|
```suggestion
|`reverse`|       |Remove this role instead of adding it to the member.|
```

2021-10-03 01:59 UTC, 4norak commented on moderation/verification/documentation.md
> +The `password` subcommand sets the *secret* password the user will need to verify with.
```suggestion
The `password` subcommand sets the *secret* password the member will need to verify with.
```

2021-10-04 17:07 UTC, 4norak approved these changes

2021-10-04 17:09 UTC, Defelo approved these changes

2021-10-04 17:10 UTC, merged